"""ECG preprocessing shared by training, the Python runtime and the Dart port.

Training and on-device inference MUST apply byte-for-byte the same transform,
otherwise a model that scores well offline silently degrades on the phone.
So the filter is implemented here explicitly (Direct-Form-II-transposed
biquads + scipy's odd-extension filtfilt) instead of calling scipy at runtime.
scipy is only used once, to design the coefficients, which are then exported
as constants for lib/ml/ecg_preprocess.dart.

Pipeline: resample to WINDOW -> zero-phase bandpass -> zero-mean -> peak-normalise
"""
from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

import numpy as np

FS_HZ = 360.0          # MIT-BIH rate; the ESP32 must send this or be resampled to it
WINDOW = 256           # samples fed to the CNN (~0.71 s at 360 Hz)
BAND = (0.5, 45.0)
ORDER = 4


@lru_cache(maxsize=1)
def coefficients() -> tuple[np.ndarray, np.ndarray]:
    """(sos [n,6], zi [n,2]) - designed once with scipy."""
    from scipy.signal import butter, sosfilt_zi
    high = min(BAND[1], FS_HZ / 2 * 0.99)
    sos = butter(ORDER, [BAND[0], high], btype="bandpass", fs=FS_HZ, output="sos")
    return sos, sosfilt_zi(sos)


def _sosfilt(sos: np.ndarray, x: np.ndarray, zi: np.ndarray) -> np.ndarray:
    y = x.astype(np.float64).copy()
    z = zi.astype(np.float64).copy()
    for s in range(sos.shape[0]):
        b0, b1, b2, _, a1, a2 = sos[s]
        z0, z1 = z[s]
        for i in range(y.size):
            xi = y[i]
            yi = b0 * xi + z0
            z0 = b1 * xi - a1 * yi + z1
            z1 = b2 * xi - a2 * yi
            y[i] = yi
    return y


def filtfilt(x: np.ndarray) -> np.ndarray:
    """Equivalent to scipy.signal.sosfiltfilt(sos, x, padlen=min(3*(2n+1), len-1))."""
    sos, zi = coefficients()
    x = np.asarray(x, dtype=np.float64)
    pad = min(3 * (2 * sos.shape[0] + 1), x.size - 1)
    if pad < 1:
        return x - x.mean()
    ext = np.concatenate((2 * x[0] - x[pad:0:-1], x, 2 * x[-1] - x[-2:-pad - 2:-1]))
    y = _sosfilt(sos, ext, zi * ext[0])
    y = _sosfilt(sos, y[::-1], zi * y[-1])[::-1]
    return y[pad:-pad]


def preprocess(raw) -> np.ndarray:
    """Raw ADC window (any length >= 10) -> float32 (1, 1, WINDOW) model input."""
    x = np.asarray(raw, dtype=np.float64)
    if x.size < 10:
        raise ValueError("ECG window too short")
    if x.size != WINDOW:
        x = np.interp(np.linspace(0, 1, WINDOW), np.linspace(0, 1, x.size), x)
    y = filtfilt(x)
    y -= y.mean()
    peak = np.abs(y).max()
    if peak > 0:
        y /= peak
    return y.astype(np.float32).reshape(1, 1, WINDOW)


def export_constants(path: Path) -> None:
    sos, zi = coefficients()
    path.write_text(json.dumps({"fs_hz": FS_HZ, "window": WINDOW, "band": BAND,
                                "order": ORDER, "sos": sos.tolist(), "zi": zi.tolist()}))


def preprocess_batch(windows: np.ndarray) -> np.ndarray:
    """Vectorised version for training (N, WINDOW) -> (N, 1, WINDOW).

    Uses scipy.sosfiltfilt, which is proven identical to filtfilt() above by
    tests/test_ecg_preprocess.py; the loop version is too slow for 100k beats.
    """
    from scipy.signal import sosfiltfilt
    sos, _ = coefficients()
    w = np.asarray(windows, dtype=np.float64)
    if w.shape[1] != WINDOW:
        raise ValueError(f"expected windows of {WINDOW}")
    pad = min(3 * (2 * sos.shape[0] + 1), WINDOW - 1)
    y = sosfiltfilt(sos, w, axis=-1, padlen=pad)
    y -= y.mean(axis=1, keepdims=True)
    peak = np.abs(y).max(axis=1, keepdims=True)
    y = np.divide(y, peak, out=y, where=peak > 0)
    return y.astype(np.float32)[:, None, :]


if __name__ == "__main__":
    # python ecg_preprocess.py <raksha-dash root>  -> Dart preprocessing fixture
    import sys
    root = Path(sys.argv[1] if len(sys.argv) > 1 else ".")
    fx = root / "test" / "fixtures"
    fx.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(3)
    rows = []
    for n in (10, 64, WINDOW, 400):                  # includes resample + short-pad paths
        raw = (512 + 80 * np.sin(np.linspace(0, 12, n)) + rng.normal(0, 15, n)).round()
        rows.append({"raw": raw.tolist(), "out": preprocess(raw)[0, 0].tolist()})
    sos, zi = coefficients()
    (fx / "ecg_preprocess_parity.json").write_text(
        json.dumps({"sos": sos.tolist(), "zi": zi.tolist(), "rows": rows}))
    print("wrote", fx / "ecg_preprocess_parity.json")
    rl = lambda a: ", ".join(repr(float(v)) for v in np.ravel(a))
    lib = root / "lib" / "ml"
    lib.mkdir(parents=True, exist_ok=True)
    (lib / "ecg_preprocess.dart").write_text(f"""// GENERATED by ecg_preprocess.py - DO NOT EDIT. Mirrors ecg_preprocess.preprocess().
import 'dart:typed_data';

const int kEcgWindow = {WINDOW};
const double kEcgFsHz = {FS_HZ};
const int _nSec = {sos.shape[0]};
const List<double> _sos = [{rl(sos)}]; // rows of [b0,b1,b2,a0,a1,a2]
const List<double> _zi = [{rl(zi)}];   // rows of [z0,z1]

void _sosfilt(List<double> y, double scale) {{
  for (var s = 0; s < _nSec; s++) {{
    final b0 = _sos[s * 6], b1 = _sos[s * 6 + 1], b2 = _sos[s * 6 + 2];
    final a1 = _sos[s * 6 + 4], a2 = _sos[s * 6 + 5];
    var z0 = _zi[s * 2] * scale, z1 = _zi[s * 2 + 1] * scale;
    for (var i = 0; i < y.length; i++) {{
      final xi = y[i];
      final yi = b0 * xi + z0;
      z0 = b1 * xi - a1 * yi + z1;
      z1 = b2 * xi - a2 * yi;
      y[i] = yi;
    }}
  }}
}}

/// Raw ECG window (>= 10 samples, at [kEcgFsHz]) -> model input of length
/// [kEcgWindow]. Reshape to [1, 1, kEcgWindow] for tflite_flutter.
Float32List preprocessEcg(List<num> raw) {{
  final n = raw.length;
  if (n < 10) throw ArgumentError('ECG window too short');
  final x = List<double>.filled(kEcgWindow, 0);
  for (var i = 0; i < kEcgWindow; i++) {{
    if (n == kEcgWindow) {{ x[i] = raw[i].toDouble(); continue; }}
    final pos = i * (n - 1) / (kEcgWindow - 1);
    var lo = pos.floor();
    if (lo > n - 2) lo = n - 2;
    final f = pos - lo;
    x[i] = raw[lo] + (raw[lo + 1] - raw[lo]) * f;
  }}
  final pad = 3 * (2 * _nSec + 1) < kEcgWindow - 1 ? 3 * (2 * _nSec + 1) : kEcgWindow - 1;
  final ext = <double>[
    for (var k = pad; k >= 1; k--) 2 * x[0] - x[k],
    ...x,
    for (var k = 2; k <= pad + 1; k++) 2 * x[kEcgWindow - 1] - x[kEcgWindow - k],
  ];
  _sosfilt(ext, ext.first);
  final rev = ext.reversed.toList();
  _sosfilt(rev, rev.first);
  final y = rev.reversed.toList().sublist(pad, pad + kEcgWindow);
  var mean = 0.0;
  for (final v in y) {{ mean += v; }}
  mean /= y.length;
  var peak = 0.0;
  for (var i = 0; i < y.length; i++) {{
    y[i] -= mean;
    if (y[i].abs() > peak) peak = y[i].abs();
  }}
  return Float32List.fromList([for (final v in y) peak > 0 ? v / peak : v]);
}}
""")
    print("wrote", lib / "ecg_preprocess.dart")


R_PEAK_OFFSET = 99          # samples before the R-peak in every training window


def beat_windows(raw, fs: float = FS_HZ) -> list:
    """Split an ECG strip into R-peak-aligned WINDOW-sample raw windows.

    A strip no longer than ~1.2 windows is assumed to be one pre-aligned beat
    (what the ESP32 sends if it does its own R detection). Longer strips are
    band-passed, peaks found on |signal| (polarity-agnostic), and each beat is
    cut exactly like the training data: [R - 99, R + 157).
    """
    from scipy.signal import find_peaks, sosfiltfilt
    x = np.asarray(raw, dtype=np.float64)
    if abs(fs - FS_HZ) > 1e-6:
        n = int(round(x.size * FS_HZ / fs))
        x = np.interp(np.linspace(0, 1, n), np.linspace(0, 1, x.size), x)
    if x.size <= int(1.2 * WINDOW):
        return [x]
    sos, _ = coefficients()
    env = np.abs(sosfiltfilt(sos, x - x.mean()))
    peaks, _ = find_peaks(env, height=0.45 * np.percentile(env, 99.5),
                          distance=int(0.25 * FS_HZ))
    return [x[p - R_PEAK_OFFSET:p - R_PEAK_OFFSET + WINDOW] for p in peaks
            if p - R_PEAK_OFFSET >= 0 and p - R_PEAK_OFFSET + WINDOW <= x.size]
